name: repository synchronization
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.KEY }}
          upstream_repository: KarolMaliglowka/AirSensorApiClient
          target_repository: KarolMaliglowka/AirQualitySite
          upstream_branch: master
          target_branch: develop
          force: true
          tags: true
